---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Robo-Dancers
description: Code your own dance moves!
original_url: https://codeclubprojects.org/en-GB/strictly-robo-boogie/robo-dancers
interests: ''
technologies: ''
site_areas: codeclub, strictly-robo-boogie
steps:
- title: Introduction
- title: Getting started
- title: Customising your dance
- title: 'Challenge: Don''t lose your head'
- title: Code mode
- title: 'Challenge: Create your own dance'
- title: Dancing to bars
- title: 'Challenge: Changing dance'

