---
hero_image: images/robo-dancers.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Robo-Dancers
description: Code your own dance moves!
original_url: https://codeclubprojects.org/en-GB/strictly-robo-boogie/robo-dancers
interests: ''
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Getting started
- title: Customising your dance
- title: 'Challenge: Don''t lose your head'
- title: Code mode
- title: 'Challenge: Create your own dance'
- title: Dancing to bars
  completion: internal
- title: 'Challenge: Changing dance'
